### ISSUE TITLE
Code to apply PLATON to CNN architechures

### ISSUE THREAD

**Issue by amitchandak** [QingruZhang/PLATON#1]
Hi,
Can you please share code to apply PLATON to CNN models like VGG-16, ResNet, etc..

Thank you,
Amit

**Comment by QingruZhang** [comment]
Hello, 
We have not implemented PLATON for CNN and ResNet. You can import Pruner module to iteratively prune CNN. Please follow the instructions in  README to achieve it. Thanks.
