### ISSUE TITLE
Sparse models available for download?

### ISSUE THREAD

**Issue by eldarkurtic** [QingruZhang/PLATON#2]
Hello :-)

I found your paper very interesting and would like to play with the sparse models that PLATON produced. Are you going to open-source them soon?

**Comment by QingruZhang** [comment]
Hello, 
Thanks for your interest in our paper. I just open-sourced the code of GLUE. Our results are reproducable. You could directly run the scripts to prune a pre-trained model and get the sparsified model. Thanks.

**Comment by eldarkurtic** [comment]
Okay, thanks a lot for the update.
